### PR TITLE
Feature/49 remove half implemented feature

### LINKED ISSUE #49: Move half-implemented features to a dev-branch
Cleanup is needed

### PR DESCRIPTION
**Pull request by M-Blomqvist**
Closes #49 Is it a good idea to have a `dev` branch? Me thinkest so, Removed code is retained there.

### CODE REVIEW

**Comment by M-Blomqvist** [comment]
Should be merged after #51

**Review by isakvlarsson — APPROVED** [review]
dev branch is cool B)

**Review by axellervik — COMMENTED** [review]
rip force/mod.rs 

(you won't be missed)

**Review by axellervik — APPROVED** [review]
very well cleaned up!

**Pull request merged**
